# Generated by Django 3.0.7 on 2020-06-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('sNo', models.IntegerField(primary_key=True, serialize=False)),
                ('article', models.CharField(max_length=500)),
                ('fullText', models.TextField(max_length=10000)),
            ],
        ),
    ]
