# Generated by Django 3.1.2 on 2020-10-28 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDetail',
            fields=[
                ('sNo', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('reservations', models.TextField(max_length=500)),
                ('article', models.CharField(max_length=500)),
                ('fullText', models.TextField(max_length=10000)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countryArticles.countrydetail')),
            ],
        ),
    ]
