# Generated by Django 3.1.2 on 2020-10-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countryArticles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetail',
            name='active',
            field=models.CharField(max_length=10),
        ),
    ]
