# Generated by Django 3.1.2 on 2020-10-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countryArticles', '0002_auto_20201028_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetail',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
