# Generated by Django 3.1.2 on 2020-10-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countryArticles', '0003_auto_20201028_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetail',
            name='article',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='reservations',
            field=models.TextField(max_length=10000),
        ),
    ]
