# Generated by Django 3.1.2 on 2020-10-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countryArticles', '0004_auto_20201028_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetail',
            name='date',
            field=models.CharField(max_length=5000),
        ),
    ]
